// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pvms.DAL;

#nullable disable

namespace Pvms.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230319120756_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pvms.DAL.Entities.SpecializationInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SpecializationInfos");
                });

            modelBuilder.Entity("Pvms.DAL.Entities.UserStatistics", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("B121Count")
                        .HasColumnType("int");

                    b.Property<int>("B122Count")
                        .HasColumnType("int");

                    b.Property<int>("B123Count")
                        .HasColumnType("int");

                    b.Property<int>("BachelorCount")
                        .HasColumnType("int");

                    b.Property<int>("M121Count")
                        .HasColumnType("int");

                    b.Property<int>("M122Count")
                        .HasColumnType("int");

                    b.Property<int>("M123Count")
                        .HasColumnType("int");

                    b.Property<int>("MasterCount")
                        .HasColumnType("int");

                    b.Property<int>("StartCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
